### PR TITLE
trivial: fix typo

### PR DESCRIPTION
**Pull request by axel-h**
Signed-off-by: Axel Heider <axelheider@gmx.de>

### CODE REVIEW

**Comment by nomadeel** [comment]
@ssrg-bamboo `test`

**Comment by nomadeel** [comment]
Nice catch!

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Pull request merged**
