### PR TITLE
Set SIMULATION for Spike platform by default

### PR DESCRIPTION
**Pull request by Ivan-Velickovic**
The following command for building seL4test for the Spike (as documented here https://docs.sel4.systems/Hardware/spike.html) will not compile: `../init-build.sh -DPLATFORM=spike -DRISCV64=1`. This is because the CMake variable `SIMULATION` is not set so seL4test is trying to initialise a timer for the Spike, which isn't implemented. This patch turns `SIMULATION` on for the Spike by default, matching the behaviour for the QEMU AArch64 `virt` platform.

### CODE REVIEW

**Comment by axel-h** [comment]
Seems the github CI workflows set `SIMULATION=TRUE` automatically, so this issues did never popped up here.

**Review by axel-h — APPROVED** [review]
Looks good to me.

**Review by lsf37 — APPROVED** [review]
Looks good!

Can you please wait with merging it until the machine queue is fully recovered and we've had a successful sel4test run on seL4? (hopefully just one board left to fix)

**Comment by axel-h** [comment]
@lsf37 yes. Sorry, I did not pay attention to that detail. Shame on me.

**Comment by lsf37** [comment]
> @lsf37 yes. Sorry, I did not pay attention to that detail. Shame on me.

No worries, the merge on seL4 actually turned out to be good, because my re-run from last night didn't pick up the sel4test merge (which I think is the correct behaviour, I just forgot that it would do that). Anyway, I hope we'll be able to sort out the remaining issues today.

**Comment by lsf37** [comment]
The `imx8mq2` board is broken (issues with the serial port), so I've disabled that for now and we can merge again.

**Pull request merged**
