### PR TITLE
Test range max against defined number

### PR DESCRIPTION
**Pull request by jdub**

### CODE REVIEW

**Comment by jdub** [comment]
Couldn't figure out how to combine a preprocessor constant and integer suffix, so switched to test_assert.

**Comment by Smattr** [comment]
You might have some success with something like `JOIN(CONFIG_RETYPE_FAN_OUT_LIMIT, ul)` using the definition from utils/stringify.h.

**Comment by AdrianDanis** [comment]
Can also just do an explicit cast like ` (unsigned long)CONFIG_RETYPE_FAN_OUT_LIMIT`

**Comment by jdub** [comment]
Thanks -- the explicit cast seemed neater. Tested on sabre/qemu and x64/qemu.

**Pull request merged**
