### PR TITLE
Speedup Tests

### PR DESCRIPTION
**Pull request by Indanz**
This more than halves the time to run all tests.

### CODE REVIEW

**Comment by Indanz** [comment]
All checks passed, let's try hw tests now.

**Comment by Indanz** [comment]
Only test failing is `MULTICORE0005` on gcc TX2 and I didn't change that one.

**Comment by Indanz** [comment]
The main time is spend in CI overhead and board bring up, so running the tests in CI still takes forever. :-(

**Comment by kent-mcleod** [comment]
> The main time is spend in CI overhead and board bring up, so running the tests in CI still takes forever. :-(

In some cases the board bring-up times can usually be optimized because each board is run with a custom run script that usually introduces the delays.

But some boards take a long time from power on to the u-boot prompt. This could also be optimized but someone would need to rebuild the boards boot firmware.

I think the CI overhead is still what dominates though.

**Review by kent-mcleod — APPROVED** [review]

**Comment by Indanz** [comment]
> But some boards take a long time from power on to the u-boot prompt. This could also be optimized but someone would need to rebuild the boards boot firmware.

Switching from tftp boot to USB boot via UUU for NXP based SoCs would probably save a fair bit. Newer SoCs also seem to have built-in board control and can e.g. be power cycled via USB with https://github.com/nxp-imx/bcu.

> I think the CI overhead is still what dominates though.

I think there are some suboptimal things going on there. For instance, the last CI had to wait an hour for a lock to become free. The lock was held by the next CI run. That seems fairly bizarre to me. On one hand CI runs release the lock in between all tests, on the other hand it can block a board for an hour?

Thanks for the review!

**Comment by Ivan-Velickovic** [comment]
> Switching from tftp boot to USB boot via UUU for NXP based SoCs would probably save a fair bit. Newer SoCs also seem to have built-in board control and can e.g. be power cycled via USB with https://github.com/nxp-imx/bcu.

I've noticed that the ethernet drivers in U-Boot are generally quite poor so for a lot of boards it can take up to a half a minute or so to just load an image (although for sel4test the images are fairly small so maybe it doesn't matter).

Given that the USB drivers would also be polling-based would it actually be any better?

**Comment by Indanz** [comment]
> Given that the USB drivers would also be polling-based would it actually be any better?

I don't know, I set the board in serial boot mode and use UUU to upload SPL+Uboot,
then start Uboot in Fastboot mode and run Uboot commands from UUU, including
loading the image and booting it. All that takes 4 seconds from power-on to the first
Elfloader print.

I can share the UUU script I'm using if anyone is interested.

**Pull request merged**
