### PR TITLE
PolarFire SoC: Initial Support

### PR DESCRIPTION
**Pull request by Jesse-Millwood**
Disable huge page for the Polarfire platform
Turn timer tests off for the Polarfire platform

### CODE REVIEW

**Comment by abrandnewusername** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit c38e96b49f1832ca8367ec0fffb33cb79075caf1

### Summary

| Test name | Result |
| --- | --- |
| Code Quality - Check licenses - sel4test - EXT-dornerworks-polarfire-support-24 | SUCCESSFUL |
| Code Quality - Style - sel4test - EXT-dornerworks-polarfire-support-24 | FAILED |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - sel4test - EXT-dornerworks-polarfire-support-24 | Style check on changed files | 1 of 3 jobs failed |

**Job: style**
Build logs

    17-Sep-2020 15:55:11	Build Code Quality - Style - sel4test - EXT-dornerworks-polarfire-support-24 - style #1 (CQ-SEL4TESTSTYLE64-SEL4TESTSTYLEPR-1) started building on agent A local agent 2
    17-Sep-2020 15:55:11	I run on the Bamboo server!
    17-Sep-2020 15:55:11	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4TESTSTYLE64-SEL4TESTSTYLEPR
    17-Sep-2020 15:55:11	Executing build Code Quality - Style - sel4test - EXT-dornerworks-polarfire-support-24 - style #1 (CQ-SEL4TESTSTYLE64-SEL4TESTSTYLEPR-1)
    17-Sep-2020 15:55:11	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4TESTSTYLE64-SEL4TESTSTYLEPR/. (location: .)
    17-Sep-2020 15:55:11	Artifact 'code' prepared in 24.08 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4TESTSTYLE64-SEL4TESTSTYLEPR/./code.tar.gz
    17-Sep-2020 15:55:11	Running pre-build action: VCS Version Collector
    17-Sep-2020 15:55:11	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    17-Sep-2020 15:55:11	+ tar xf code.tar.gz --recursive-unlink
    17-Sep-2020 15:55:11	Finished task 'Untar code' with result: Success
    17-Sep-2020 15:55:11	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    17-Sep-2020 15:55:11	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4TESTSTYLE64-SEL4TESTSTYLEPR
    17-Sep-2020 15:55:11	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    17-Sep-2020 15:55:11	Starting task 'Check style of changed files' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    17-Sep-2020 15:55:12	+ cd sel4test
    17-Sep-2020 15:55:12	+ xargs -d '\n' /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4TESTSTYLE64-SEL4TESTSTYLEPR/seL4_tools/misc/style.sh
    17-Sep-2020 15:55:12	++ git merge-base c38e96b49f1832ca8367ec0fffb33cb79075caf1 ffefb10d785fd3490ecc4d2a1922395867750889
    17-Sep-2020 15:55:12	+ git diff --name-only c38e96b49f1832ca8367ec0fffb33cb79075caf1 6f73c4d2741012a362fc6d24bbdee63a343db5ad
    17-Sep-2020 15:55:12	Unchanged  apps/sel4test-tests/arch/riscv/arch_frame_type.h
    17-Sep-2020 15:55:12	+ git diff --exit-code
    17-Sep-2020 15:55:12	diff --git a/settings.cmake b/settings.cmake
    17-Sep-2020 15:55:12	index ec9dd01..9240e9f 100644
    17-Sep-2020 15:55:12	--- a/settings.cmake
    17-Sep-2020 15:55:12	+++ b/settings.cmake
    17-Sep-2020 15:55:12	@@ -80,8 +80,11 @@ if(NOT Sel4testAllowSettingsOverride)
    17-Sep-2020 15:55:12	         else()
    17-Sep-2020 15:55:12	             set(Sel4testHaveTimer OFF CACHE BOOL "" FORCE)
    17-Sep-2020 15:55:12	         endif()
    17-Sep-2020 15:55:12	-    elseif(KernelPlatformZynqmp OR KernelPlatformPolarfire OR
    17-Sep-2020 15:55:12	-            (SIMULATION AND (KernelArchRiscV OR KernelArchARM)))
    17-Sep-2020 15:55:12	+    elseif(
    17-Sep-2020 15:55:12	+        KernelPlatformZynqmp
    17-Sep-2020 15:55:12	+        OR KernelPlatformPolarfire
    17-Sep-2020 15:55:12	+        OR (SIMULATION AND (KernelArchRiscV OR KernelArchARM))
    17-Sep-2020 15:55:12	+    )
    17-Sep-2020 15:55:12	         # Frequency settings of the ZynqMP make the ltimer tests problematic
    17-Sep-2020 15:55:12	         # Polarfire does not have a complete ltimer implementation
    17-Sep-2020 15:55:12	         set(Sel4testHaveTimer OFF CACHE BOOL "" FORCE)
    17-Sep-2020 15:55:12	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-SEL4TESTSTYLE64-SEL4TESTSTYLEPR-1-ScriptBuildTask-2609953644443891439.sh] was 1 while expected 0
    17-Sep-2020 15:55:12	Finished task 'Check style of changed files' with result: Failed
    17-Sep-2020 15:55:12	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    17-Sep-2020 15:55:12	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4TESTSTYLE64-SEL4TESTSTYLEPR
    17-Sep-2020 15:55:12	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    17-Sep-2020 15:55:12	Starting task 'Run astyle code insights' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    17-Sep-2020 15:55:12	+ cd sel4test
    17-Sep-2020 15:55:12	++ echo ssh://git@bitbucket.keg.ertos.in.nicta.com.au:7999/sel4/sel4test.git
    17-Sep-2020 15:55:12	++ cut -d/ -f4
    17-Sep-2020 15:55:12	+ bb_proj=sel4
    17-Sep-2020 15:55:12	+ /scripts/bb_code_insights/create_code_insights.sh astyle sel4 sel4test
    17-Sep-2020 15:55:12	++ dirname /scripts/bb_code_insights/create_code_insights.sh
    17-Sep-2020 15:55:12	+ SCRIPT_DIR=/scripts/bb_code_insights
    17-Sep-2020 15:55:12	+ BBS_URL=https://bitbucket.ts.data61.csiro.au
    17-Sep-2020 15:55:12	+ BBS_PROJECT=sel4
    17-Sep-2020 15:55:12	+ BBS_REPO=sel4test
    17-Sep-2020 15:55:12	+ REPORT_TO_RUN=astyle
    17-Sep-2020 15:55:12	++ git rev-parse HEAD
    17-Sep-2020 15:55:12	+ COMMIT_ID=c38e96b49f1832ca8367ec0fffb33cb79075caf1
    17-Sep-2020 15:55:12	+ REPORT_KEY=astyle.report
    17-Sep-2020 15:55:12	+ set +x
    17-Sep-2020 15:55:12	+ report_file=astyle_report.json
    17-Sep-2020 15:55:12	+ annotations_file=astyle_annotations.json
    17-Sep-2020 15:55:12	+ rm -f astyle_report.json astyle_annotations.json
    17-Sep-2020 15:55:12	+ /scripts/bb_code_insights/astyle
    17-Sep-2020 15:55:15	Reporting on these files:  ['apps/sel4test-driver/src/main.c', 'apps/sel4test-tests/arch/riscv/arch_frame_type.h', 'apps/sel4test-tests/src/tests/scheduler.c']
    17-Sep-2020 15:55:15	+ echo 'Reporting the results to BitBucket, but doing so *secretly*, so people don'\''t see the access token'
    17-Sep-2020 15:55:15	Reporting the results to BitBucket, but doing so *secretly*, so people don't see the access token
    17-Sep-2020 15:55:15	+ set +x
    17-Sep-2020 15:55:15	+ '[' -f astyle_report.json ']'
    17-Sep-2020 15:55:15	+ cat astyle_report.json
    17-Sep-2020 15:55:15	+ '[' -f astyle_annotations.json ']'
    17-Sep-2020 15:55:15	{"data":[{"title":"Total number of files with incorrect style","value":0},{"title":"Total number of lines with incorrect style","value":0}],"createdDate":1600322115766,"key":"astyle.report","title":"Code style"}{"title": "Code style", "data": [{"title": "Total number of files with incorrect style", "value": 0}, {"title": "Total number of lines with incorrect style", "value": 0}]}
    17-Sep-2020 15:55:15	Finished task 'Run astyle code insights' with result: Success
    17-Sep-2020 15:55:15	Running post build plugin 'NCover Results Collector'
    17-Sep-2020 15:55:15	Running post build plugin 'Artifact Copier'
    17-Sep-2020 15:55:15	Running post build plugin 'npm Cache Cleanup'
    17-Sep-2020 15:55:15	Running post build plugin 'Clover Results Collector'
    17-Sep-2020 15:55:15	Running post build plugin 'Docker Container Cleanup'
    17-Sep-2020 15:55:15	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4TESTSTYLE64-SEL4TESTSTYLEPR'
    17-Sep-2020 15:55:15	Finalising the build...
    17-Sep-2020 15:55:15	Stopping timer.
    17-Sep-2020 15:55:15	Build CQ-SEL4TESTSTYLE64-SEL4TESTSTYLEPR-1 completed.
    17-Sep-2020 15:55:15	Running on server: post build plugin 'NCover Results Collector'
    17-Sep-2020 15:55:15	Running on server: post build plugin 'Build Hanging Detection Configuration'
    17-Sep-2020 15:55:15	Running on server: post build plugin 'Clover Delta Calculator'
    17-Sep-2020 15:55:15	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    17-Sep-2020 15:55:15	All post build plugins have finished
    17-Sep-2020 15:55:15	Generating build results summary...
    17-Sep-2020 15:55:15	Saving build results to disk...
    17-Sep-2020 15:55:15	Store variable context...
    17-Sep-2020 15:55:15	Indexing build results...
    17-Sep-2020 15:55:15	Finished building CQ-SEL4TESTSTYLE64-SEL4TESTSTYLEPR-1.


This is the most I can report on right now, sorry!

**Comment by Jesse-Millwood** [comment]
Do I just need to run astyle here?

**Comment by abrandnewusername** [comment]
Sorry again for the slow respond, it looks good to me.
Can you please fix the style?

**Comment by Jesse-Millwood** [comment]
I just ran astyle on the two file that I changed and pushed it. I ran `astyle --options=../../tools/seL4/misc/astylerc <files>` and it only changed part of the `settings.cmake`. Is that all that is needed?

**Comment by abrandnewusername** [comment]
Yes, astyle only changes files that need to be fixed.
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit 0d1eae830db49e1e008c1252cb3497ca5c974d08

### Summary

#### NOTE: some test results have been updated!

| Test name | Result |
| --- | --- |
| Code Quality - Check licenses - sel4test - EXT-dornerworks-polarfire-support-24 | SUCCESSFUL |
| Code Quality - Style - sel4test - EXT-dornerworks-polarfire-support-24 | FAILED |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - sel4test - EXT-dornerworks-polarfire-support-24 | Style check on changed files | 1 of 3 jobs failed |

**Job: style**
Build logs

    19-Sep-2020 12:56:39	Build Code Quality - Style - sel4test - EXT-dornerworks-polarfire-support-24 - style #2 (CQ-SEL4TESTSTYLE64-SEL4TESTSTYLEPR-2) started building on agent A local agent 1
    19-Sep-2020 12:56:39	I run on the Bamboo server!
    19-Sep-2020 12:56:39	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TESTSTYLE64-SEL4TESTSTYLEPR
    19-Sep-2020 12:56:39	Executing build Code Quality - Style - sel4test - EXT-dornerworks-polarfire-support-24 - style #2 (CQ-SEL4TESTSTYLE64-SEL4TESTSTYLEPR-2)
    19-Sep-2020 12:56:39	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TESTSTYLE64-SEL4TESTSTYLEPR/. (location: .)
    19-Sep-2020 12:56:39	Artifact 'code' prepared in 29.10 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TESTSTYLE64-SEL4TESTSTYLEPR/./code.tar.gz
    19-Sep-2020 12:56:39	Running pre-build action: VCS Version Collector
    19-Sep-2020 12:56:39	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    19-Sep-2020 12:56:39	+ tar xf code.tar.gz --recursive-unlink
    19-Sep-2020 12:56:39	Finished task 'Untar code' with result: Success
    19-Sep-2020 12:56:39	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    19-Sep-2020 12:56:39	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TESTSTYLE64-SEL4TESTSTYLEPR
    19-Sep-2020 12:56:39	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    19-Sep-2020 12:56:39	Starting task 'Check style of changed files' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    19-Sep-2020 12:56:39	+ cd sel4test
    19-Sep-2020 12:56:39	+ xargs -d '\n' /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TESTSTYLE64-SEL4TESTSTYLEPR/seL4_tools/misc/style.sh
    19-Sep-2020 12:56:39	++ git merge-base 0d1eae830db49e1e008c1252cb3497ca5c974d08 ffefb10d785fd3490ecc4d2a1922395867750889
    19-Sep-2020 12:56:39	+ git diff --name-only 0d1eae830db49e1e008c1252cb3497ca5c974d08 6f73c4d2741012a362fc6d24bbdee63a343db5ad
    19-Sep-2020 12:56:39	Unchanged  apps/sel4test-tests/arch/riscv/arch_frame_type.h
    19-Sep-2020 12:56:40	+ git diff --exit-code
    19-Sep-2020 12:56:40	diff --git a/settings.cmake b/settings.cmake
    19-Sep-2020 12:56:40	index 1ba405d..08b83f0 100644
    19-Sep-2020 12:56:40	--- a/settings.cmake
    19-Sep-2020 12:56:40	+++ b/settings.cmake
    19-Sep-2020 12:56:40	@@ -13,7 +13,14 @@
    19-Sep-2020 12:56:40	 cmake_minimum_required(VERSION 3.7.2)
    19-Sep-2020 12:56:40	 
    19-Sep-2020 12:56:40	 set(project_dir "${CMAKE_CURRENT_LIST_DIR}/../../")
    19-Sep-2020 12:56:40	-file(GLOB project_modules $ {project_dir} / projects/*)
    19-Sep-2020 12:56:40	+file(
    19-Sep-2020 12:56:40	+    GLOB
    19-Sep-2020 12:56:40	+        project_modules
    19-Sep-2020 12:56:40	+        $
    19-Sep-2020 12:56:40	+        {project_dir}
    19-Sep-2020 12:56:40	+        /
    19-Sep-2020 12:56:40	+        projects/*
    19-Sep-2020 12:56:40	+)
    19-Sep-2020 12:56:40	 list(
    19-Sep-2020 12:56:40	     APPEND
    19-Sep-2020 12:56:40	         CMAKE_MODULE_PATH
    19-Sep-2020 12:56:40	@@ -80,8 +87,11 @@ if(NOT Sel4testAllowSettingsOverride)
    19-Sep-2020 12:56:40	         else()
    19-Sep-2020 12:56:40	             set(Sel4testHaveTimer OFF CACHE BOOL "" FORCE)
    19-Sep-2020 12:56:40	         endif()
    19-Sep-2020 12:56:40	-    elseif(KernelPlatformZynqmp OR KernelPlatformPolarfire OR
    19-Sep-2020 12:56:40	-            (SIMULATION AND (KernelArchRiscV OR KernelArchARM)))
    19-Sep-2020 12:56:40	+    elseif(
    19-Sep-2020 12:56:40	+        KernelPlatformZynqmp
    19-Sep-2020 12:56:40	+        OR KernelPlatformPolarfire
    19-Sep-2020 12:56:40	+        OR (SIMULATION AND (KernelArchRiscV OR KernelArchARM))
    19-Sep-2020 12:56:40	+    )
    19-Sep-2020 12:56:40	         # Frequency settings of the ZynqMP make the ltimer tests problematic
    19-Sep-2020 12:56:40	         # Polarfire does not have a complete ltimer implementation
    19-Sep-2020 12:56:40	         set(Sel4testHaveTimer OFF CACHE BOOL "" FORCE)
    19-Sep-2020 12:56:40	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-SEL4TESTSTYLE64-SEL4TESTSTYLEPR-2-ScriptBuildTask-2353199467236255656.sh] was 1 while expected 0
    19-Sep-2020 12:56:40	Finished task 'Check style of changed files' with result: Failed
    19-Sep-2020 12:56:40	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    19-Sep-2020 12:56:40	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TESTSTYLE64-SEL4TESTSTYLEPR
    19-Sep-2020 12:56:41	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    19-Sep-2020 12:56:41	Starting task 'Run astyle code insights' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    19-Sep-2020 12:56:41	+ cd sel4test
    19-Sep-2020 12:56:41	++ echo ssh://git@bitbucket.keg.ertos.in.nicta.com.au:7999/sel4/sel4test.git
    19-Sep-2020 12:56:41	++ cut -d/ -f4
    19-Sep-2020 12:56:41	+ bb_proj=sel4
    19-Sep-2020 12:56:41	+ /scripts/bb_code_insights/create_code_insights.sh astyle sel4 sel4test
    19-Sep-2020 12:56:41	++ dirname /scripts/bb_code_insights/create_code_insights.sh
    19-Sep-2020 12:56:41	+ SCRIPT_DIR=/scripts/bb_code_insights
    19-Sep-2020 12:56:41	+ BBS_URL=https://bitbucket.ts.data61.csiro.au
    19-Sep-2020 12:56:41	+ BBS_PROJECT=sel4
    19-Sep-2020 12:56:41	+ BBS_REPO=sel4test
    19-Sep-2020 12:56:41	+ REPORT_TO_RUN=astyle
    19-Sep-2020 12:56:41	++ git rev-parse HEAD
    19-Sep-2020 12:56:41	+ COMMIT_ID=0d1eae830db49e1e008c1252cb3497ca5c974d08
    19-Sep-2020 12:56:41	+ REPORT_KEY=astyle.report
    19-Sep-2020 12:56:41	+ set +x
    19-Sep-2020 12:56:41	+ report_file=astyle_report.json
    19-Sep-2020 12:56:41	+ annotations_file=astyle_annotations.json
    19-Sep-2020 12:56:41	+ rm -f astyle_report.json astyle_annotations.json
    19-Sep-2020 12:56:41	+ /scripts/bb_code_insights/astyle
    19-Sep-2020 12:56:43	Reporting on these files:  ['apps/sel4test-driver/src/main.c', 'apps/sel4test-tests/arch/riscv/arch_frame_type.h', 'apps/sel4test-tests/src/tests/scheduler.c']
    19-Sep-2020 12:56:43	+ echo 'Reporting the results to BitBucket, but doing so *secretly*, so people don'\''t see the access token'
    19-Sep-2020 12:56:43	+ set +x
    19-Sep-2020 12:56:43	Reporting the results to BitBucket, but doing so *secretly*, so people don't see the access token
    19-Sep-2020 12:56:46	+ '[' -f astyle_report.json ']'
    19-Sep-2020 12:56:46	+ cat astyle_report.json
    19-Sep-2020 12:56:46	+ '[' -f astyle_annotations.json ']'
    19-Sep-2020 12:56:46	{"data":[{"title":"Total number of files with incorrect style","value":0},{"title":"Total number of lines with incorrect style","value":0}],"createdDate":1600484205935,"key":"astyle.report","title":"Code style"}{"title": "Code style", "data": [{"title": "Total number of files with incorrect style", "value": 0}, {"title": "Total number of lines with incorrect style", "value": 0}]}
    19-Sep-2020 12:56:46	Finished task 'Run astyle code insights' with result: Success
    19-Sep-2020 12:56:46	Running post build plugin 'NCover Results Collector'
    19-Sep-2020 12:56:46	Running post build plugin 'Artifact Copier'
    19-Sep-2020 12:56:46	Running post build plugin 'npm Cache Cleanup'
    19-Sep-2020 12:56:46	Running post build plugin 'Clover Results Collector'
    19-Sep-2020 12:56:46	Running post build plugin 'Docker Container Cleanup'
    19-Sep-2020 12:56:46	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TESTSTYLE64-SEL4TESTSTYLEPR'
    19-Sep-2020 12:56:46	Finalising the build...
    19-Sep-2020 12:56:46	Stopping timer.
    19-Sep-2020 12:56:46	Build CQ-SEL4TESTSTYLE64-SEL4TESTSTYLEPR-2 completed.
    19-Sep-2020 12:56:46	Running on server: post build plugin 'NCover Results Collector'
    19-Sep-2020 12:56:46	Running on server: post build plugin 'Build Hanging Detection Configuration'
    19-Sep-2020 12:56:46	Running on server: post build plugin 'Clover Delta Calculator'
    19-Sep-2020 12:56:46	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    19-Sep-2020 12:56:46	All post build plugins have finished
    19-Sep-2020 12:56:46	Generating build results summary...
    19-Sep-2020 12:56:46	Saving build results to disk...
    19-Sep-2020 12:56:46	Store variable context...
    19-Sep-2020 12:56:46	Indexing build results...
    19-Sep-2020 12:56:46	Finished building CQ-SEL4TESTSTYLE64-SEL4TESTSTYLEPR-2.


This is the most I can report on right now, sorry!

**Comment by abrandnewusername** [comment]
Hmmm, I guess instead of astyle, you might want to try `../../tools/seL4/misc/style.sh <files>`, this is the same style checker as bamboo uses. Sorry for the troubles.

**Comment by abrandnewusername** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by abrandnewusername** [comment]
Ooops, the PR doesn't seem to be rebased against the latest master. Would you like to try that again? Or I'm happy to rebase it for you, but I don't seem to have the permission.

**Comment by abrandnewusername** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Pull request merged**
